### ISSUE TITLE
New referral design Functionality issues - Mobile and desktop

### ISSUE THREAD

**Issue by QAgurinder-Dhiman** [Navdeepqa/qa#5]

**Comment by QAgurinder-Dhiman** [comment]
1. Unable to select current date in date of birth field and still validation showing after selecting DOB.
   Proof :- https://screenrec.com/share/YicFh1kNJx
**Fixed**

2. Unable to add new Medical practice when user added all necesary feild and tap on submit button.
Proof :- https://screenrec.com/share/Ec8Kgb5F7t 
**Fixed**

3. Design getting destroyed when user refreshing the screen or landing on MP creation feild.
Proof :- https://prnt.sc/ehInNkSJCUyi , https://screenrec.com/share/Fw1qPhZv6r 

4. Please show any default any placeholder or apply any validation message when user tap on join button without selecting any exing MP.
Proof :- https://prnt.sc/4LcGqwwT19lQ 
Live  :- https://prnt.sc/reB9EYIkUO7j 

5. Mandatory field icon not displaying when user tap on "Save" icon without filling mandatory fields.
Proof :- https://prnt.sc/n2Xi2k2pO1Jo
@bilalzafar1 **Validation should not be applied. Please remove. and update here**

**Comment by suruchideve** [comment]
@bilalzafar1 Please check above issues

**Comment by QAgurinder-Dhiman** [comment]
6. Working but old design displaying after deleting last referral 
Proof :- https://screenrec.com/share/372tDmAKu6 
**Fixed**

7. User is not able to go next page of MP 
Proof :- https://screenrec.com/share/6VUeALbOzq 
**Fixed**

8. User is not able to leave the MP 
Proof :- https://screenrec.com/share/1pLIeZCAES 
**Fixed**

**Comment by suruchideve** [comment]
_> 1. Unable to select current date in date of birth field and still validation showing after selecting DOB.
>    Proof :- https://screenrec.com/share/YicFh1kNJx_
_> 2. Unable to add new Medical practice when user added all necesary feild and tap on submit button.
>    Proof :- https://screenrec.com/share/Ec8Kgb5F7t_
> 3. Design getting destroyed when user refreshing the screen or landing on MP creation feild.
>    Proof :- https://prnt.sc/ehInNkSJCUyi , https://screenrec.com/share/Fw1qPhZv6r
> 4. Please show any default any placeholder or apply any validation message when user tap on join button without selecting any exing MP.
>    Proof :- https://prnt.sc/4LcGqwwT19lQ
>    Live  :- https://prnt.sc/reB9EYIkUO7j
> 5. Mandatory field icon not displaying when user tap on "Save" icon without filling mandatory fields.
>    Proof :- https://prnt.sc/n2Xi2k2pO1Jo

**Comment by Navdeepqa** [comment]
Re-opened as it was closed by mistake

**Comment by Rajnishsharma01** [comment]
@QAgurinder-Dhiman 
3.Done

**Comment by bilalzafar1** [comment]
@QAgurinder-Dhiman 
4.Done
5.Done

**Comment by QAgurinder-Dhiman** [comment]
9. Please show qualification in next line 
Proof :- https://img001.prntscr.com/file/img001/4jSGvLcwSoyl2dRG7J2dBw.png 

10. "Provider number" heading is displaying with number.
Proof :- https://img001.prntscr.com/file/img001/c3HG2W1zTm6YHazOs4USpQ.png 

11. Need to add one space between these test for better enhancement.
Proof :- https://img001.prntscr.com/file/img001/Malm0w7-SRePpvfdFIs81w.png 

12. Reason to referral validation message is not displaying when user try to delete referral without any reason.
Proof :- https://img001.prntscr.com/file/img001/_KUwvKwKQeG9gEysa9trJQ.png https://img001.prntscr.com/file/img001/6gwnArDsTwigOjIIifRvVw.png 

13. Screen is not getting refreshed or user should be go back sent/inbox section after all deletion of referral
Proof :- https://screenrec.com/share/RHqj8KJQNC

**Comment by bilalzafar1** [comment]
@QAgurinder-Dhiman 
9.Done
10.Done
11.Done

**Comment by Navdeepqa** [comment]
@Rajnishsharma01 @bilalzafar1 @suruchideve 
Plz check below for functional issues

N1.No month and year are displayed in calendar for all DOb fields in add patient window
Proof:https://prnt.sc/d0bDwIN1ycPO

N2.Add button is not working in Add Patient window
Proof:https://screenrec.com/share/6vIVxQOowT

N3.While adding files in consult notes, even if file is uploaded then also "file uploading' is showing
Proof:https://screenrec.com/share/J5ZdNsw4aj

N4.Sex field value is not fetched when the patient is searched from the search Patient and selected
Proof:https://screenrec.com/share/YQ0VJZyN9R

N5.If there is new received refferral in the inbox, the count badge on HP"s image icon from whom the referral is received is shown in the other two pages like sent and draft pages also
Proof:https://screenrec.com/share/F5JfPY6hey

N6.Should this be "0 result" or "no result found"?
Proof:https://img001.prntscr.com/file/img001/UJcawA7WTyGxZLDZQ3NIfg.png

N7.”saved to draft successfully" message is not displayed when saving draft button is clicked
Proof:https://screenrec.com/share/0gRresKYom

N8.Back arrow icon does not redirect to HP's list page on Inbox, sent draft pages
Proof:https://screenrec.com/share/37Ro2BO1HE

N9.In the Pathology form, the test requested field is not auto-populated with the list of tests
Proof:https://screenrec.com/share/nxXMCIkStm

N10.When browser size is decreased, design is getting disorted on inbox, sent, draft pages
Proof:https://img001.prntscr.com/file/img001/f9TVP8QAQZSDtwAqb1Un8g.png

N11.When the size decreased, the Select word disappeared in the patient search listed
Proof:https://screenrec.com/share/Cq9MGrK3LB

N12.In decreased browser size, the select button is not displayed properly for offline HPs
Proof:https://screenrec.com/share/cQPGd02l1U

N13.In decreased browser size, the downward arrow is not displayed for offline HP's
Proof:https://img001.prntscr.com/file/img001/GbZez_DmRVy3vzdMEc48MA.png

**Comment by Rajnishsharma01** [comment]
@Navdeepqa 
N10. working fine from my side please text again
N11:Done
N12.Done
N13.Done

**Comment by Rajnishsharma01** [comment]
@Navdeepqa 
2.Done

**Comment by QAgurinder-Dhiman** [comment]
14. Empty place holder displaying when user joined any Existing MP and tap on input field of MP.
Proof :- https://screenrec.com/share/fnaVh5o89r 

15. Old design is displaying when user refreshed the MP page and while refreshing click on search bar 
Proof :- https://screenrec.com/share/xrWTVwdZkc 

16. Local V2 page UI displaying when user Joined any new MP practice after 10 recodes and click on next page.
Proof :- https://screenrec.com/share/4YWQbxdtMK 

17. User have to search again the same user to select when user search the patient and click on hyperlink to view the patient detail.
Proof :- https://screenrec.com/share/hnJKiVGdpl
